Asteria/force-app/main/default/objects/CardPayment__c/CardPayment__c.object-meta.xml
<CustomObject>
    <label>CardPayment</label>
    <nameField>
        <label>CardPayment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CardPayments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Asteria/force-app/main/default/objects/CardPayment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CardPayments</relationshipLabel>
    <relationshipName>CardPayments</relationshipName>
    <type>Lookup</type>
</CustomField>

Asteria/force-app/main/default/classes/AuraPaymentController.cls
public class AuraPaymentController {
    @AuraEnabled
    public static Id getAccountPayment(){
       	Id currentUserID = UserInfo.getUserId();
        system.debug('CurrentUserID: '+ currentUserID);
        Id currentUserAccount = [SELECT accountId FROM User WHERE id=:currentUserID LIMIT 1].accountId;
        system.debug('currentUserAccount: '+ currentUserAccount);
        CardPayment__c cardPayment = [SELECT id FROM CardPayment__c WHERE Account__c= :currentUserAccount LIMIT 1];
        //CardPayment__c cardPayment = [SELECT id FROM CardPayment__c WHERE Account__c= '0015e000004xiA9AAI' LIMIT 1];
        System.debug('Card Payment: '+cardPayment.id);
        return cardPayment.id;
    } 

}