Asteria/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Ores, minerals, and other materials in Inventory are available for Purchase.</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>Inv-{00000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Asteria/force-app/main/default/objects/Inventory__c/fields/Item_Price__c.field-meta.xml
<CustomField>
    <fullName>Item_Price__c</fullName>
    <formula>CASE(Unit_Price__c,
  &quot;$1,000&quot;, 1000,
  &quot;$50,000&quot;, 50000,
  &quot;$100,000&quot;, 100000,
  &quot;$250,000&quot;, 250000,
  &quot;$1,000,000&quot;, 1000000,
  &quot;$5,000,000&quot;, 5000000,
null) * Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Item_Price_Text__c.field-meta.xml
<CustomField>
    <fullName>Item_Price_Text__c</fullName>
    <formula>IF( Item_Price__c &gt;= 9999999.00,
&quot;$&quot; &amp; (TEXT(Item_Price__c / 1000000)) &amp; &quot; MM&quot;,
&quot;$&quot; &amp; (TEXT(Item_Price__c / 1000)) &amp; &quot; K&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Price (Text)</label>
    <type>Text</type>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Mining_Site_List__c.field-meta.xml
<CustomField>
    <fullName>Mining_Site_List__c</fullName>
    <description>The Mining Site where this ore was extracted.</description>
    <inlineHelpText>The Mining Site where this ore was extracted.</inlineHelpText>
    <label>Mining Site</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mining_Site</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Mothership__c.field-meta.xml
<CustomField>
    <fullName>Mothership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mothership</label>
    <referenceTo>Mothership__c</referenceTo>
    <relationshipLabel>Inventory</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Number_Of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Orders__c</fullName>
    <description>Sums up the numbers of Purchase Orders for Inventory.</description>
    <inlineHelpText>Sums up the numbers of Purchase Orders for Inventory.</inlineHelpText>
    <label>Number Of Orders</label>
    <summaryForeignKey>Purchase_Orders__c.Inventory__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Ore_Type__c.field-meta.xml
<CustomField>
    <fullName>Ore_Type__c</fullName>
    <description>The type of ore indicated for this Inventory record.</description>
    <inlineHelpText>The type of ore indicated for this Inventory record.</inlineHelpText>
    <label>Ore Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Inventory</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes whether the Inventory item is &apos;New&apos;, is &apos;Pending&apos; approval, or has been &apos;Approved&apos;.</description>
    <inlineHelpText>Describes whether the Inventory item is &apos;New&apos;, is &apos;Pending&apos; approval, or has been &apos;Approved&apos;.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Rejected__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>The Weight of this ore measured in GSU (Galactic Standard Units).</description>
    <inlineHelpText>The Weight of this ore measured in GSU (Galactic Standard Units).</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Asteria/force-app/main/default/objects/Mothership__c/Mothership__c.object-meta.xml
<CustomObject>
    <description>The Mothership: a large spacecraft or ship from which smaller craft are launched or maintained. Mobile headquarters of Asteria Deep Space Mining Co.</description>
    <label>Mothership</label>
    <nameField>
        <label>Mothership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Motherships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Asteria/force-app/main/default/objects/Purchase_Orders__c/Purchase_Orders__c.object-meta.xml
<CustomObject>
    <description>Accounts place Purchase Orders for ore in Inventory.</description>
    <label>Purchase Orders</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Account making the Purchase.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Purchases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <description>The Inventory being Purchased by an Account.</description>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipName>Purchases</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Type__c</fullName>
    <formula>TEXT(Inventory__r.Ore_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Type</label>
    <type>Text</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Inventory_Weight__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Weight__c</fullName>
    <formula>Inventory__r.Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This Purchase Order is either New, Pending, or Approved.</description>
    <inlineHelpText>This Purchase Order is either New, Pending, or Approved.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Rejected__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/globalValueSets/Inventory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Iridium</fullName>
    </customValue>
    <customValue>
        <fullName>Palladium</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum</fullName>
    </customValue>
    <customValue>
        <fullName>Rhodium</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <description>A list of ores contained in Inventory.</description>
    <masterLabel>Inventory</masterLabel>
</GlobalValueSet>

Asteria/force-app/main/default/globalValueSets/Mining_Site.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Astyanax (1871)</fullName>
    </customValue>
    <customValue>
        <fullName>Helicaon (30942)</fullName>
    </customValue>
    <customValue>
        <fullName>Lykaon (4792)</fullName>
    </customValue>
    <customValue>
        <fullName>Neleus (136557)</fullName>
    </customValue>
    <customValue>
        <fullName>Palamedes (2456)</fullName>
    </customValue>
    <customValue>
        <fullName>Yperion (184280)</fullName>
    </customValue>
    <description>A list of asteroids designated as Mining Sites.</description>
    <masterLabel>Mining Site</masterLabel>
</GlobalValueSet>

Asteria/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <description>New, Pending, or Approved.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

Asteria/force-app/main/default/classes/AuraStoreController.cls
public without sharing class AuraStoreController {
    
    //return inventoryList based off no orders
    @AuraEnabled
    public static List<Inventory__c> getInventoryList(){
    	List<Inventory__c> availableInventoryList = [SELECT Id, Name, Mining_Site_List__c, Status__c, Mothership__r.Name, Ore_Type__c, Weight__c, Item_Price_Text__c 
                                                 FROM Inventory__c 
                                                 WHERE Status__c='Approved' 
                                                 AND Number_of_Orders__c = 0 
                                                 ORDER BY Item_Price__c 
                                                 ASC];
    	return availableInventoryList;
 	}
    
    //Add InventoryListToCart
    @AuraEnabled
    public static void addInventoryListToCart(List<Id> inventoryList){
        Id userAcct = getAccountId();
        List<Purchase_Orders__c> newOrders = new List<Purchase_Orders__c>();
        for(Id invId : inventoryList){
            Purchase_Orders__c newOrder = new Purchase_Orders__c(Account__c = userAcct, Inventory__c = invId, Status__c='New');
            newOrders.add(newOrder);
        }
        system.debug(newOrders);
		Database.SaveResult[] srList = Database.insert(newOrders, false);
        for(Database.SaveResult sr : srList){
            system.debug(sr.isSuccess());
            system.debug(sr.getId());
        }
    }
    
    //orderType is the Status of the order and will return a mapped list for different uses based on location of component
    //FIGURE OUT HOW TO ADD PHOTOS!!!!
    @AuraEnabled
    public static Map<String, List<Purchase_Orders__c>> getPurchaseOrdersByType(String orderType){
        Id userAcct = getAccountID();
        String queryTemplate = 'SELECT Id, Name, Account__c, Inventory__c, Inventory_Type__c, Inventory_Weight__c, Status__c FROM Purchase_Orders__c WHERE '+ orderType +' AND Account__c = \'' + userAcct + '\'';
        List<Purchase_Orders__c> queryOrders = Database.query(queryTemplate);
        Map<String, List<Purchase_Orders__c>> ordersByType = new Map<String, List<Purchase_Orders__c>>();
        for(Purchase_Orders__c order:queryOrders){
            if(ordersByType.containskey(order.Status__c)){
                ordersByType.get(order.Status__c).add(order);
            }else{
                List<Purchase_Orders__C> newList = new List<Purchase_Orders__c>{order};
                ordersByType.put(order.Status__c, newList);
            }
        }
        return ordersByType;             
    }
    
    //get all pictures from Single Item

    
    //returns id of current User
    @testVisible
    private static Id getAccountID(){
        Id userId = UserInfo.getUserId();
        Id userAcct = [SELECT accountId FROM User WHERE id=:userId].accountId;
        return userAcct;
    }
}