Asteria/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Ores, minerals, and other materials in Inventory are available for Purchase.</description>
    <label>Inventory</label>
    <nameField>
        <displayFormat>Inv-{00000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Asteria/force-app/main/default/objects/Inventory__c/fields/Mining_Site_List__c.field-meta.xml
<CustomField>
    <fullName>Mining_Site_List__c</fullName>
    <description>The Mining Site where this ore was extracted.</description>
    <inlineHelpText>The Mining Site where this ore was extracted.</inlineHelpText>
    <label>Mining Site</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mining_Site</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Ore_Type__c.field-meta.xml
<CustomField>
    <fullName>Ore_Type__c</fullName>
    <description>The type of ore indicated for this Inventory record.</description>
    <inlineHelpText>The type of ore indicated for this Inventory record.</inlineHelpText>
    <label>Ore Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Inventory</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes whether the Inventory item is &apos;New&apos;, is &apos;Pending&apos; approval, or has been &apos;Approved&apos;.</description>
    <inlineHelpText>Describes whether the Inventory item is &apos;New&apos;, is &apos;Pending&apos; approval, or has been &apos;Approved&apos;.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Rejected__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/objects/Inventory__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>The Weight of this ore measured in GSU (Galactic Standard Units).</description>
    <inlineHelpText>The Weight of this ore measured in GSU (Galactic Standard Units).</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/Purchase_Orders__c.object-meta.xml
<CustomObject>
    <description>Accounts place Purchase Orders for ore in Inventory.</description>
    <label>Purchase Orders</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Account making the Purchase.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Purchases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <description>The Inventory being Purchased by an Account.</description>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipName>Purchases</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Asteria/force-app/main/default/objects/Purchase_Orders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This Purchase Order is either New, Pending, or Approved.</description>
    <inlineHelpText>This Purchase Order is either New, Pending, or Approved.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Rejected__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

Asteria/force-app/main/default/globalValueSets/Inventory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Diamond</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Iridium</fullName>
    </customValue>
    <customValue>
        <fullName>Palladium</fullName>
    </customValue>
    <customValue>
        <fullName>Platinum</fullName>
    </customValue>
    <customValue>
        <fullName>Rhodium</fullName>
    </customValue>
    <customValue>
        <fullName>Silver</fullName>
    </customValue>
    <description>A list of ores contained in Inventory.</description>
    <masterLabel>Inventory</masterLabel>
</GlobalValueSet>

Asteria/force-app/main/default/globalValueSets/Mining_Site.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Astyanax (1871)</fullName>
    </customValue>
    <customValue>
        <fullName>Helicaon (30942)</fullName>
    </customValue>
    <customValue>
        <fullName>Lykaon (4792)</fullName>
    </customValue>
    <customValue>
        <fullName>Neleus (136557)</fullName>
    </customValue>
    <customValue>
        <fullName>Palamedes (2456)</fullName>
    </customValue>
    <customValue>
        <fullName>Yperion (184280)</fullName>
    </customValue>
    <description>A list of asteroids designated as Mining Sites.</description>
    <masterLabel>Mining Site</masterLabel>
</GlobalValueSet>

Asteria/force-app/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <description>New, Pending, or Approved.</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

Asteria/force-app/main/default/classes/AuraStoreControllerTest.cls
@isTest
public class AuraStoreControllerTest {
    

    @TestSetup
    static void testSetup(){
        
        List<Inventory__c> testInventory = new List<Inventory__c>();
        
        for(Integer i = 0;  i < 50; i++){
            Inventory__c testSingle = new Inventory__c();
            if(i < 25){
                testSingle.Status__c = 'New';
                testSingle.Mining_Site_List__c = 'Astyanax (1871)';
                testSingle.Ore_Type__c = 'Gold';
            	testSingle.Weight__c = 2.5;
                testInventory.add(testSingle);
            }else{
                testSingle.Status__c = 'Approved';
                testSingle.Mining_Site_List__c = 'Astyanax (1871)';
                testSingle.Ore_Type__c = 'Gold';
                testSingle.Weight__c = 2.5;
                testInventory.add(testSingle);
            }
        }
        
        Database.insert(testInventory);

        Account partnerAccount = new Account();
        partnerAccount.Name ='partner';
        
        Database.insert(partnerAccount);
        
        partnerAccount.isPartner = true;
        
        Database.update(partnerAccount);
        
        Contact partnerContact = new Contact();
        partnerContact.LastName = 'test';
        partnerContact.AccountId = partnerAccount.Id;
        
        Database.insert(partnerContact);
        
        Id partnerProfileId = [SELECT id FROM Profile WHERE name='Asteria Partner' Limit 1].id;
        Id partnerRoleId = [Select Id From UserRole Where PortalType = 'None' Limit 1].id;
        
        User partnerUser = new User(
            ProfileId = partnerProfileId,
            Username = System.now().millisecond() + 'test42@test.com',
            Alias = 'Hath',
            Email='Hath.Annaway@mgail.com',
            EmailEncodingKey='UTF-8',
            Firstname='Hath',
            Lastname='Annaway',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago',
            ContactId = partnerContact.id
        );
        
        Database.insert(partnerUser);
    }
    
    @isTest
    static void getInventoryReturnsInventory(){
       
       List<Inventory__c> approvedItems = AuraStoreController.getInventoryList();
        System.assertEquals(25, approvedItems.size());
        for(Inventory__c item:approvedItems){
            System.assertEquals('Approved', item.status__c);
        }
        
    }
    
    @isTest 
    static void getAccountReturnsAccount(){
		Id accountId = [SELECT id FROM ACCOUNT WHERE NAME='Partner'].Id;
        User partnerUser = [SELECT id, name FROM User WHERE alias='Hath'];
        System.runAs(partnerUser){
           Id partnerAccountId = AuraStoreController.getAccountId();
           System.assertEquals(accountId, partnerAccountId);
        }  
    }
    
    @isTest
    static void addInventoryAddsToCart(){
        User partnerUser = [SELECT id, name FROM User WHERE alias='Hath'];
        Id accountId = [SELECT id FROM ACCOUNT WHERE NAME='Partner'Limit 1].Id;
        List<Inventory__c> addPurchaseOrder = [SELECT id, Ore_Type__c FROM Inventory__c WHERE status__c = 'Approved'];
        List<Purchase_Orders__c> OrdersToAdd = new List<Purchase_Orders__c>();
        for(Integer i = 0; i < addPurchaseOrder.size(); i++){
            if(Math.mod(i, 2) != 0){
            OrdersToAdd.add(new Purchase_Orders__c(Account__c = accountId, Inventory__c=addPurchaseOrder[i].Id, status__c = 'New'));
            }
        }
        insert OrdersToAdd;
        List<Inventory__c> inventoryList = [SELECT id FROM Inventory__C WHERE status__c = 'Approved'];
        List<Id> InventoryToAdd = new List<Id>();
        
        for(Inventory__c item:inventoryList){
             InventoryToAdd.add(item.Id);
       	}

        System.runAs(partnerUser){
            Test.startTest();
        	List<Integer> outOfStock = auraStoreController.addInventoryListToCart(inventoryToAdd);
            Test.stopTest();
            List<Purchase_Orders__c> newOrders = [SELECT id, Name FROM Purchase_Orders__c WHERE Account__c=:accountId];
        	system.debug(newOrders);
            system.assertEquals(12, newOrders.size());
            system.assertEquals(12, outOfStock.size());
            
            for(Integer i : outOfStock){
                system.assert(Math.mod(i, 2) != 0);
            }
        }
        
        
    }
    
    @isTest
    static void getPurchaseOrdersByTypeTest(){
        Id accountId = [SELECT id FROM ACCOUNT WHERE NAME='partner'].Id;
        User partnerUser = [SELECT id, name FROM User WHERE alias='Hath'];
        List<Inventory__c> inv = [SELECT id FROM Inventory__c WHERE Status__c='Approved'];
        List<Purchase_Orders__c> orderList = new List<Purchase_Orders__C>();
        for(Integer i = 0; i < 25; i++){
            //FIX FOR ACCOUNT WHEN LIVE
        	Purchase_Orders__c newOrder = new Purchase_Orders__c(Account__c = '0015e000005FvciAAC', Inventory__c = inv[i].id);    
            //Purchase_Orders__c newOrder = new Purchase_Orders__c(Account__c = accountId, Inventory__c = inv[i].id);    
            if(i < 8){
                newOrder.status__c = 'New';
            }
            else if(i < 16){
                newOrder.status__c = 'Pending';
            }else{
                newOrder.status__c = 'Approved';
            }
            orderList.add(newOrder);
        }
        Database.insert(orderList);
        
        System.runAs(partnerUser){
            
            Test.startTest();
            Map<String, List<Purchase_Orders__c>> orders = auraStoreController.getPurchaseOrdersByType();
            system.debug(orders);
            List<Purchase_Orders__c> newOrders = orders.get('New');
            List<Purchase_Orders__c> pendingOrders = orders.get('Pending');
        	List<Purchase_Orders__c> approvedOrders = orders.get('Approved');
            Test.stopTest();
            
            System.assertEquals(8, newOrders.size());
            System.assertEquals(8, pendingOrders.size());
            System.assertEquals(9, approvedOrders.size());        
        }
    }
    
    @isTest
    static void deletePurchaseOrderDeletes(){
        Id accountId = [SELECT id FROM ACCOUNT WHERE NAME='partner'].Id;
        User partnerUser = [SELECT id, name FROM User WHERE alias='Hath'];
        Id inv = [SELECT id FROM Inventory__c WHERE Status__c='Approved' Limit 1].Id;
        Purchase_Orders__c newOrder = new Purchase_Orders__c(Account__c = accountId, Inventory__c = inv, Status__c = 'New');
        
        System.runAs(partnerUser){
            insert newOrder;
            List<Purchase_Orders__c> newOrders = [SELECT id FROM Purchase_Orders__c];
            system.assertEquals(1, newOrders.size());
            auraStoreController.deletePurchaseOrder(newOrder.id);
            List<Purchase_Orders__c> deletedOrders = [SELECT id FROM Purchase_Orders__c];
            system.assertEquals(0, deletedOrders.size());
            
        }
        
   
        
    }
    
}